/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Argument from './Argument';
import Context from './Context';
import PermissionBulkCheckRequestItem from './PermissionBulkCheckRequestItem';
import PermissionCheckRequestMetadata from './PermissionCheckRequestMetadata';

/**
 * The BulkCheckBody model module.
 * @module model/BulkCheckBody
 * @version 0.11.0
 */
class BulkCheckBody {
    /**
     * Constructs a new <code>BulkCheckBody</code>.
     * PermissionBulkCheckRequest is the request message for the BulkCheck method in the Permission service.
     * @alias module:model/BulkCheckBody
     */
    constructor() { 
        
        BulkCheckBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkCheckBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkCheckBody} obj Optional instance to populate.
     * @return {module:model/BulkCheckBody} The populated <code>BulkCheckBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkCheckBody();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = PermissionCheckRequestMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PermissionBulkCheckRequestItem]);
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = Context.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], [Argument]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkCheckBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkCheckBody</code>.
     */
    static validateJSON(data) {
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          PermissionCheckRequestMetadata.validateJSON(data['metadata']);
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                PermissionBulkCheckRequestItem.validateJSON(item);
            };
        }
        // validate the optional field `context`
        if (data['context']) { // data not null
          Context.validateJSON(data['context']);
        }
        if (data['arguments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['arguments'])) {
                throw new Error("Expected the field `arguments` to be an array in the JSON data but got " + data['arguments']);
            }
            // validate the optional field `arguments` (array)
            for (const item of data['arguments']) {
                Argument.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/PermissionCheckRequestMetadata} metadata
 */
BulkCheckBody.prototype['metadata'] = undefined;

/**
 * List of permission check requests, maximum 100 items.
 * @member {Array.<module:model/PermissionBulkCheckRequestItem>} items
 */
BulkCheckBody.prototype['items'] = undefined;

/**
 * @member {module:model/Context} context
 */
BulkCheckBody.prototype['context'] = undefined;

/**
 * Additional arguments associated with this request.
 * @member {Array.<module:model/Argument>} arguments
 */
BulkCheckBody.prototype['arguments'] = undefined;






export default BulkCheckBody;

