/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.10.1
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Any from './Any';
import Subjects from './Subjects';
import Values from './Values';

/**
 * The ExpandLeaf model module.
 * @module model/ExpandLeaf
 * @version v0.10.1
 */
class ExpandLeaf {
    /**
     * Constructs a new <code>ExpandLeaf</code>.
     * ExpandLeaf is the leaf node of an Expand tree and can be either a set of Subjects or a set of Values.
     * @alias module:model/ExpandLeaf
     */
    constructor() { 
        
        ExpandLeaf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExpandLeaf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExpandLeaf} obj Optional instance to populate.
     * @return {module:model/ExpandLeaf} The populated <code>ExpandLeaf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExpandLeaf();

            if (data.hasOwnProperty('subjects')) {
                obj['subjects'] = Subjects.constructFromObject(data['subjects']);
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = Values.constructFromObject(data['values']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = Any.constructFromObject(data['value']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExpandLeaf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExpandLeaf</code>.
     */
    static validateJSON(data) {
        // validate the optional field `subjects`
        if (data['subjects']) { // data not null
          Subjects.validateJSON(data['subjects']);
        }
        // validate the optional field `values`
        if (data['values']) { // data not null
          Values.validateJSON(data['values']);
        }

        return true;
    }


}



/**
 * @member {module:model/Subjects} subjects
 */
ExpandLeaf.prototype['subjects'] = undefined;

/**
 * @member {module:model/Values} values
 */
ExpandLeaf.prototype['values'] = undefined;

/**
 * @member {module:model/Any} value
 */
ExpandLeaf.prototype['value'] = undefined;






export default ExpandLeaf;

