/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Component from './Component';
import Version from './Version';

/**
 * The Extension model module.
 * @module model/Extension
 * @version 0.11.0
 */
class Extension {
    /**
     * Constructs a new <code>Extension</code>.
     * An extension that was requested for the source expression.
     * @alias module:model/Extension
     */
    constructor() { 
        
        Extension.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Extension</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Extension} obj Optional instance to populate.
     * @return {module:model/Extension} The populated <code>Extension</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Extension();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('affectedComponents')) {
                obj['affectedComponents'] = ApiClient.convertToType(data['affectedComponents'], [Component]);
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = Version.constructFromObject(data['version']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Extension</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Extension</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['affectedComponents'])) {
            throw new Error("Expected the field `affectedComponents` to be an array in the JSON data but got " + data['affectedComponents']);
        }
        // validate the optional field `version`
        if (data['version']) { // data not null
          Version.validateJSON(data['version']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
Extension.prototype['id'] = undefined;

/**
 * If set, the listed components must understand the extension for the expression to evaluate correctly.  This field has set semantics, repeated values should be deduplicated.
 * @member {Array.<module:model/Component>} affectedComponents
 */
Extension.prototype['affectedComponents'] = undefined;

/**
 * @member {module:model/Version} version
 */
Extension.prototype['version'] = undefined;






export default Extension;

