/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Argument from './Argument';
import Context from './Context';
import Entity from './Entity';
import PermissionLookupSubjectRequestMetadata from './PermissionLookupSubjectRequestMetadata';
import RelationReference from './RelationReference';

/**
 * The LookupSubjectBody model module.
 * @module model/LookupSubjectBody
 * @version 0.11.0
 */
class LookupSubjectBody {
    /**
     * Constructs a new <code>LookupSubjectBody</code>.
     * PermissionLookupSubjectRequest is the request message for the LookupSubject method in the Permission service.
     * @alias module:model/LookupSubjectBody
     */
    constructor() { 
        
        LookupSubjectBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LookupSubjectBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LookupSubjectBody} obj Optional instance to populate.
     * @return {module:model/LookupSubjectBody} The populated <code>LookupSubjectBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LookupSubjectBody();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = PermissionLookupSubjectRequestMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('entity')) {
                obj['entity'] = Entity.constructFromObject(data['entity']);
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
            if (data.hasOwnProperty('subject_reference')) {
                obj['subject_reference'] = RelationReference.constructFromObject(data['subject_reference']);
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = Context.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], [Argument]);
            }
            if (data.hasOwnProperty('page_size')) {
                obj['page_size'] = ApiClient.convertToType(data['page_size'], 'Number');
            }
            if (data.hasOwnProperty('continuous_token')) {
                obj['continuous_token'] = ApiClient.convertToType(data['continuous_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LookupSubjectBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LookupSubjectBody</code>.
     */
    static validateJSON(data) {
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          PermissionLookupSubjectRequestMetadata.validateJSON(data['metadata']);
        }
        // validate the optional field `entity`
        if (data['entity']) { // data not null
          Entity.validateJSON(data['entity']);
        }
        // ensure the json data is a string
        if (data['permission'] && !(typeof data['permission'] === 'string' || data['permission'] instanceof String)) {
            throw new Error("Expected the field `permission` to be a primitive type in the JSON string but got " + data['permission']);
        }
        // validate the optional field `subject_reference`
        if (data['subject_reference']) { // data not null
          RelationReference.validateJSON(data['subject_reference']);
        }
        // validate the optional field `context`
        if (data['context']) { // data not null
          Context.validateJSON(data['context']);
        }
        if (data['arguments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['arguments'])) {
                throw new Error("Expected the field `arguments` to be an array in the JSON data but got " + data['arguments']);
            }
            // validate the optional field `arguments` (array)
            for (const item of data['arguments']) {
                Argument.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['continuous_token'] && !(typeof data['continuous_token'] === 'string' || data['continuous_token'] instanceof String)) {
            throw new Error("Expected the field `continuous_token` to be a primitive type in the JSON string but got " + data['continuous_token']);
        }

        return true;
    }


}



/**
 * @member {module:model/PermissionLookupSubjectRequestMetadata} metadata
 */
LookupSubjectBody.prototype['metadata'] = undefined;

/**
 * @member {module:model/Entity} entity
 */
LookupSubjectBody.prototype['entity'] = undefined;

/**
 * Permission to be checked, can be a permission or relation. Required, and must match the pattern \"^([a-zA-Z][a-zA-Z0-9_]{1,62}[a-zA-Z0-9])$\", max 64 bytes.
 * @member {String} permission
 */
LookupSubjectBody.prototype['permission'] = undefined;

/**
 * @member {module:model/RelationReference} subject_reference
 */
LookupSubjectBody.prototype['subject_reference'] = undefined;

/**
 * @member {module:model/Context} context
 */
LookupSubjectBody.prototype['context'] = undefined;

/**
 * Additional arguments associated with this request.
 * @member {Array.<module:model/Argument>} arguments
 */
LookupSubjectBody.prototype['arguments'] = undefined;

/**
 * page_size is the number of subjects to be returned in the response. The value should be between 1 and 100.
 * @member {Number} page_size
 */
LookupSubjectBody.prototype['page_size'] = undefined;

/**
 * continuous_token is an optional parameter used for pagination. It should be the value received in the previous response.
 * @member {String} continuous_token
 */
LookupSubjectBody.prototype['continuous_token'] = undefined;






export default LookupSubjectBody;

