/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.8.4
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class NullValue.
* @enum {}
* @readonly
*/
export default class NullValue {
    
        /**
         * value: "NULL_VALUE"
         * @const
         */
        "NULL_VALUE" = "NULL_VALUE";

    

    /**
    * Returns a <code>NullValue</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/NullValue} The enum <code>NullValue</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

