/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Argument from './Argument';
import Context from './Context';
import Entity from './Entity';
import PermissionExpandRequestMetadata from './PermissionExpandRequestMetadata';

/**
 * The PermissionsExpandRequest model module.
 * @module model/PermissionsExpandRequest
 * @version v0.9.9
 */
class PermissionsExpandRequest {
    /**
     * Constructs a new <code>PermissionsExpandRequest</code>.
     * PermissionExpandRequest is the request message for the Expand method in the Permission service.
     * @alias module:model/PermissionsExpandRequest
     */
    constructor() { 
        
        PermissionsExpandRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionsExpandRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionsExpandRequest} obj Optional instance to populate.
     * @return {module:model/PermissionsExpandRequest} The populated <code>PermissionsExpandRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionsExpandRequest();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = PermissionExpandRequestMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('entity')) {
                obj['entity'] = Entity.constructFromObject(data['entity']);
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = Context.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], [Argument]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PermissionsExpandRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PermissionsExpandRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          PermissionExpandRequestMetadata.validateJSON(data['metadata']);
        }
        // validate the optional field `entity`
        if (data['entity']) { // data not null
          Entity.validateJSON(data['entity']);
        }
        // ensure the json data is a string
        if (data['permission'] && !(typeof data['permission'] === 'string' || data['permission'] instanceof String)) {
            throw new Error("Expected the field `permission` to be a primitive type in the JSON string but got " + data['permission']);
        }
        // validate the optional field `context`
        if (data['context']) { // data not null
          Context.validateJSON(data['context']);
        }
        if (data['arguments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['arguments'])) {
                throw new Error("Expected the field `arguments` to be an array in the JSON data but got " + data['arguments']);
            }
            // validate the optional field `arguments` (array)
            for (const item of data['arguments']) {
                Argument.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/PermissionExpandRequestMetadata} metadata
 */
PermissionsExpandRequest.prototype['metadata'] = undefined;

/**
 * @member {module:model/Entity} entity
 */
PermissionsExpandRequest.prototype['entity'] = undefined;

/**
 * Name of the permission to be expanded, not required, must start with a letter and can include alphanumeric and underscore, max 64 bytes.
 * @member {String} permission
 */
PermissionsExpandRequest.prototype['permission'] = undefined;

/**
 * @member {module:model/Context} context
 */
PermissionsExpandRequest.prototype['context'] = undefined;

/**
 * Additional arguments associated with this request.
 * @member {Array.<module:model/Argument>} arguments
 */
PermissionsExpandRequest.prototype['arguments'] = undefined;






export default PermissionsExpandRequest;

