/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Entity from './Entity';
import Subject from './Subject';

/**
 * The PermissionBulkCheckRequestItem model module.
 * @module model/PermissionBulkCheckRequestItem
 * @version 0.11.0
 */
class PermissionBulkCheckRequestItem {
    /**
     * Constructs a new <code>PermissionBulkCheckRequestItem</code>.
     * @alias module:model/PermissionBulkCheckRequestItem
     */
    constructor() { 
        
        PermissionBulkCheckRequestItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionBulkCheckRequestItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionBulkCheckRequestItem} obj Optional instance to populate.
     * @return {module:model/PermissionBulkCheckRequestItem} The populated <code>PermissionBulkCheckRequestItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionBulkCheckRequestItem();

            if (data.hasOwnProperty('entity')) {
                obj['entity'] = Entity.constructFromObject(data['entity']);
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = Subject.constructFromObject(data['subject']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PermissionBulkCheckRequestItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PermissionBulkCheckRequestItem</code>.
     */
    static validateJSON(data) {
        // validate the optional field `entity`
        if (data['entity']) { // data not null
          Entity.validateJSON(data['entity']);
        }
        // ensure the json data is a string
        if (data['permission'] && !(typeof data['permission'] === 'string' || data['permission'] instanceof String)) {
            throw new Error("Expected the field `permission` to be a primitive type in the JSON string but got " + data['permission']);
        }
        // validate the optional field `subject`
        if (data['subject']) { // data not null
          Subject.validateJSON(data['subject']);
        }

        return true;
    }


}



/**
 * @member {module:model/Entity} entity
 */
PermissionBulkCheckRequestItem.prototype['entity'] = undefined;

/**
 * The action the user wants to perform on the resource
 * @member {String} permission
 */
PermissionBulkCheckRequestItem.prototype['permission'] = undefined;

/**
 * @member {module:model/Subject} subject
 */
PermissionBulkCheckRequestItem.prototype['subject'] = undefined;






export default PermissionBulkCheckRequestItem;

