/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionCheckResponse from './PermissionCheckResponse';

/**
 * The PermissionBulkCheckResponse model module.
 * @module model/PermissionBulkCheckResponse
 * @version 0.11.0
 */
class PermissionBulkCheckResponse {
    /**
     * Constructs a new <code>PermissionBulkCheckResponse</code>.
     * PermissionBulkCheckResponse is the response message for the BulkCheck method in the Permission service.
     * @alias module:model/PermissionBulkCheckResponse
     */
    constructor() { 
        
        PermissionBulkCheckResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionBulkCheckResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionBulkCheckResponse} obj Optional instance to populate.
     * @return {module:model/PermissionBulkCheckResponse} The populated <code>PermissionBulkCheckResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionBulkCheckResponse();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [PermissionCheckResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PermissionBulkCheckResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PermissionBulkCheckResponse</code>.
     */
    static validateJSON(data) {
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                PermissionCheckResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * List of permission check responses corresponding to each request.
 * @member {Array.<module:model/PermissionCheckResponse>} results
 */
PermissionBulkCheckResponse.prototype['results'] = undefined;






export default PermissionBulkCheckResponse;

