/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.7.7
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SchemaReadRequestMetadata from './SchemaReadRequestMetadata';

/**
 * The SchemasReadRequest model module.
 * @module model/SchemasReadRequest
 * @version v0.7.7
 */
class SchemasReadRequest {
    /**
     * Constructs a new <code>SchemasReadRequest</code>.
     * SchemaReadRequest is the request message for the Read method in the Schema service. It contains tenant_id and metadata about the schema to be read.
     * @alias module:model/SchemasReadRequest
     */
    constructor() { 
        
        SchemasReadRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SchemasReadRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SchemasReadRequest} obj Optional instance to populate.
     * @return {module:model/SchemasReadRequest} The populated <code>SchemasReadRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SchemasReadRequest();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = SchemaReadRequestMetadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SchemasReadRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SchemasReadRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          SchemaReadRequestMetadata.validateJSON(data['metadata']);
        }

        return true;
    }


}



/**
 * @member {module:model/SchemaReadRequestMetadata} metadata
 */
SchemasReadRequest.prototype['metadata'] = undefined;






export default SchemasReadRequest;

