/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.8.2
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionLookupEntityStreamResponse from './PermissionLookupEntityStreamResponse';
import Status from './Status';

/**
 * The StreamResultOfPermissionLookupEntityStreamResponse model module.
 * @module model/StreamResultOfPermissionLookupEntityStreamResponse
 * @version v0.8.2
 */
class StreamResultOfPermissionLookupEntityStreamResponse {
    /**
     * Constructs a new <code>StreamResultOfPermissionLookupEntityStreamResponse</code>.
     * @alias module:model/StreamResultOfPermissionLookupEntityStreamResponse
     */
    constructor() { 
        
        StreamResultOfPermissionLookupEntityStreamResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StreamResultOfPermissionLookupEntityStreamResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamResultOfPermissionLookupEntityStreamResponse} obj Optional instance to populate.
     * @return {module:model/StreamResultOfPermissionLookupEntityStreamResponse} The populated <code>StreamResultOfPermissionLookupEntityStreamResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamResultOfPermissionLookupEntityStreamResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = PermissionLookupEntityStreamResponse.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = Status.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StreamResultOfPermissionLookupEntityStreamResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StreamResultOfPermissionLookupEntityStreamResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          PermissionLookupEntityStreamResponse.validateJSON(data['result']);
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          Status.validateJSON(data['error']);
        }

        return true;
    }


}



/**
 * @member {module:model/PermissionLookupEntityStreamResponse} result
 */
StreamResultOfPermissionLookupEntityStreamResponse.prototype['result'] = undefined;

/**
 * @member {module:model/Status} error
 */
StreamResultOfPermissionLookupEntityStreamResponse.prototype['error'] = undefined;






export default StreamResultOfPermissionLookupEntityStreamResponse;

