/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StringArrayValue model module.
 * @module model/StringArrayValue
 * @version 0.11.0
 */
class StringArrayValue {
    /**
     * Constructs a new <code>StringArrayValue</code>.
     * Wrapper for an array of strings.
     * @alias module:model/StringArrayValue
     */
    constructor() { 
        
        StringArrayValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StringArrayValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StringArrayValue} obj Optional instance to populate.
     * @return {module:model/StringArrayValue} The populated <code>StringArrayValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StringArrayValue();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StringArrayValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StringArrayValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['data'])) {
            throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
        }

        return true;
    }


}



/**
 * The array of strings.
 * @member {Array.<String>} data
 */
StringArrayValue.prototype['data'] = undefined;






export default StringArrayValue;

