/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Status from '../model/Status';
import TenantCreateRequest from '../model/TenantCreateRequest';
import TenantCreateResponse from '../model/TenantCreateResponse';
import TenantDeleteResponse from '../model/TenantDeleteResponse';
import TenantListRequest from '../model/TenantListRequest';
import TenantListResponse from '../model/TenantListResponse';

/**
* Tenancy service.
* @module api/TenancyApi
* @version 0.11.0
*/
export default class TenancyApi {

    /**
    * Constructs a new TenancyApi. 
    * @alias module:api/TenancyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * create tenant
     * @param {module:model/TenantCreateRequest} body TenantCreateRequest is the message used for the request to create a tenant.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TenantCreateResponse} and HTTP response
     */
    tenantsCreateWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tenantsCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TenantCreateResponse;
      return this.apiClient.callApi(
        '/v1/tenants/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * create tenant
     * @param {module:model/TenantCreateRequest} body TenantCreateRequest is the message used for the request to create a tenant.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TenantCreateResponse}
     */
    tenantsCreate(body) {
      return this.tenantsCreateWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * delete tenant
     * @param {String} id id is the unique identifier of the tenant to be deleted.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TenantDeleteResponse} and HTTP response
     */
    tenantsDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling tenantsDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TenantDeleteResponse;
      return this.apiClient.callApi(
        '/v1/tenants/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * delete tenant
     * @param {String} id id is the unique identifier of the tenant to be deleted.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TenantDeleteResponse}
     */
    tenantsDelete(id) {
      return this.tenantsDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * list tenants
     * @param {module:model/TenantListRequest} body TenantListRequest is the message used for the request to list all tenants.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TenantListResponse} and HTTP response
     */
    tenantsListWithHttpInfo(body) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling tenantsList");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TenantListResponse;
      return this.apiClient.callApi(
        '/v1/tenants/list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * list tenants
     * @param {module:model/TenantListRequest} body TenantListRequest is the message used for the request to list all tenants.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TenantListResponse}
     */
    tenantsList(body) {
      return this.tenantsListWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
