/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.8.1
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PermifyApi);
  }
}(this, function(expect, PermifyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PermifyApi.Comprehension();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Comprehension', function() {
    it('should create an instance of Comprehension', function() {
      // uncomment below and update the code to test Comprehension
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be.a(PermifyApi.Comprehension);
    });

    it('should have the property iterVar (base name: "iterVar")', function() {
      // uncomment below and update the code to test the property iterVar
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

    it('should have the property iterRange (base name: "iterRange")', function() {
      // uncomment below and update the code to test the property iterRange
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

    it('should have the property accuVar (base name: "accuVar")', function() {
      // uncomment below and update the code to test the property accuVar
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

    it('should have the property accuInit (base name: "accuInit")', function() {
      // uncomment below and update the code to test the property accuInit
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

    it('should have the property loopCondition (base name: "loopCondition")', function() {
      // uncomment below and update the code to test the property loopCondition
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

    it('should have the property loopStep (base name: "loopStep")', function() {
      // uncomment below and update the code to test the property loopStep
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

    it('should have the property result (base name: "result")', function() {
      // uncomment below and update the code to test the property result
      //var instance = new PermifyApi.Comprehension();
      //expect(instance).to.be();
    });

  });

}));
