/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.7.7
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PermifyApi);
  }
}(this, function(expect, PermifyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PermifyApi.Expr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Expr', function() {
    it('should create an instance of Expr', function() {
      // uncomment below and update the code to test Expr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be.a(PermifyApi.Expr);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property constExpr (base name: "constExpr")', function() {
      // uncomment below and update the code to test the property constExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property identExpr (base name: "identExpr")', function() {
      // uncomment below and update the code to test the property identExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property selectExpr (base name: "selectExpr")', function() {
      // uncomment below and update the code to test the property selectExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property callExpr (base name: "callExpr")', function() {
      // uncomment below and update the code to test the property callExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property listExpr (base name: "listExpr")', function() {
      // uncomment below and update the code to test the property listExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property structExpr (base name: "structExpr")', function() {
      // uncomment below and update the code to test the property structExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

    it('should have the property comprehensionExpr (base name: "comprehensionExpr")', function() {
      // uncomment below and update the code to test the property comprehensionExpr
      //var instance = new PermifyApi.Expr();
      //expect(instance).to.be();
    });

  });

}));
