/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PermifyClient);
  }
}(this, function(expect, PermifyClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PermifyClient.Extension();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Extension', function() {
    it('should create an instance of Extension', function() {
      // uncomment below and update the code to test Extension
      //var instance = new PermifyClient.Extension();
      //expect(instance).to.be.a(PermifyClient.Extension);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PermifyClient.Extension();
      //expect(instance).to.be();
    });

    it('should have the property affectedComponents (base name: "affectedComponents")', function() {
      // uncomment below and update the code to test the property affectedComponents
      //var instance = new PermifyClient.Extension();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new PermifyClient.Extension();
      //expect(instance).to.be();
    });

  });

}));
