name: Js Sdk Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  update-package-json:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          node -e "
          const fs = require('fs');
          const path = './package.json';
          const pkg = require(path);
          const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
          pkg.name = repo;
          const versionParts = pkg.version.split('.');
          versionParts[2] = (parseInt(versionParts[2]) + 1).toString();
          pkg.version = versionParts.join('.');
          fs.writeFileSync(path, JSON.stringify(pkg, null, 2));
          console.log('Updated name:', pkg.name);
          console.log('Updated version:', pkg.version);
          "
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
      - run: |
          echo "Name and version from package.json:"
          cat package.json | jq '.name, .version'

